[package]
name = "pesde-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
pesde = { path = ".." }
schemars = { version = "0.8.21", features = ["semver", "url"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.131"
